import { drizzle } from "drizzle-orm/mysql2";
import { robots } from "./drizzle/schema.js";

const db = drizzle(process.env.DATABASE_URL);

const sampleRobots = [
  {
    name: "MiR250 Hook",
    manufacturer: "Mobile Industrial Robots",
    type: "mobile_base",
    length: 890,
    width: 580,
    height: 322,
    weight: 67,
    usablePayload: 250,
    functions: "Autonomous material transport, hook-based cart pulling",
    reach: null,
    driveSystem: "Differential drive",
    certifications: "ISO 3691-4, CE",
    rosCompatible: 1,
    rosDistros: "Noetic, Humble",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 540,
    batteryLife: 540,
    maxSpeed: 2000,
    forceSensor: 0,
    eoatCompatibility: null,
    armPayload: null,
    armReach: null,
    armDof: null,
    remarks: "Ideal for logistics and warehouse automation",
  },
  {
    name: "UR10e",
    manufacturer: "Universal Robots",
    type: "manipulator_arm",
    length: null,
    width: null,
    height: null,
    weight: 33,
    usablePayload: null,
    functions: "Pick and place, machine tending, packaging",
    reach: 1300,
    driveSystem: null,
    certifications: "ISO 10218-1, CE",
    rosCompatible: 1,
    rosDistros: "Noetic, Humble, Jazzy",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: null,
    batteryLife: null,
    maxSpeed: null,
    forceSensor: 1,
    eoatCompatibility: "Gripper, Suction Cup, Custom EOAT",
    armPayload: 10,
    armReach: 1300,
    armDof: 6,
    remarks: "Collaborative robot with built-in force/torque sensor",
  },
  {
    name: "Fetch Mobile Manipulator",
    manufacturer: "Fetch Robotics",
    type: "mobile_manipulator",
    length: 660,
    width: 660,
    height: 1420,
    weight: 113,
    usablePayload: 25,
    functions: "Mobile manipulation, research, warehouse automation",
    reach: 800,
    driveSystem: "Differential drive",
    certifications: "CE, FCC",
    rosCompatible: 1,
    rosDistros: "Melodic, Noetic",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 480,
    batteryLife: 480,
    maxSpeed: 1000,
    forceSensor: 0,
    eoatCompatibility: "Parallel Gripper",
    armPayload: 6,
    armReach: 800,
    armDof: 7,
    remarks: "Integrated mobile base and arm for research and industrial use",
  },
  {
    name: "KUKA KMR iiwa",
    manufacturer: "KUKA",
    type: "mobile_manipulator",
    length: 800,
    width: 600,
    height: 1800,
    weight: 220,
    usablePayload: 30,
    functions: "Flexible manufacturing, assembly, quality inspection",
    reach: 800,
    driveSystem: "Omnidirectional",
    certifications: "ISO 10218-1, ISO 3691-4, Cleanroom Class 5",
    rosCompatible: 0,
    rosDistros: null,
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 360,
    batteryLife: 360,
    maxSpeed: 1200,
    forceSensor: 1,
    eoatCompatibility: "Gripper, Suction Cup, Welding Tool",
    armPayload: 14,
    armReach: 800,
    armDof: 7,
    remarks: "Sensitive collaborative robot on mobile platform, cleanroom compatible",
  },
  {
    name: "TurtleBot 4",
    manufacturer: "Clearpath Robotics",
    type: "mobile_base",
    length: 342,
    width: 339,
    height: 351,
    weight: 9,
    usablePayload: 15,
    functions: "Research, education, SLAM, navigation",
    reach: null,
    driveSystem: "Differential drive",
    certifications: "CE, FCC",
    rosCompatible: 1,
    rosDistros: "Humble, Iron",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 240,
    batteryLife: 240,
    maxSpeed: 500,
    forceSensor: 0,
    eoatCompatibility: null,
    armPayload: null,
    armReach: null,
    armDof: null,
    remarks: "Popular research and education platform with ROS 2 support",
  },
  {
    name: "ABB IRB 1200",
    manufacturer: "ABB",
    type: "manipulator_arm",
    length: null,
    width: null,
    height: null,
    weight: 52,
    usablePayload: null,
    functions: "Assembly, material handling, machine tending",
    reach: 900,
    driveSystem: null,
    certifications: "ISO 10218-1, CE",
    rosCompatible: 0,
    rosDistros: null,
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: null,
    batteryLife: null,
    maxSpeed: null,
    forceSensor: 0,
    eoatCompatibility: "Gripper, Vacuum, Custom",
    armPayload: 7,
    armReach: 900,
    armDof: 6,
    remarks: "Compact industrial robot for small parts assembly",
  },
  {
    name: "Franka Emika Panda",
    manufacturer: "Franka Emika",
    type: "manipulator_arm",
    length: null,
    width: null,
    height: null,
    weight: 18,
    usablePayload: null,
    functions: "Research, sensitive manipulation, assembly",
    reach: 855,
    driveSystem: null,
    certifications: "CE",
    rosCompatible: 1,
    rosDistros: "Noetic, Humble",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: null,
    batteryLife: null,
    maxSpeed: null,
    forceSensor: 1,
    eoatCompatibility: "Gripper, Custom EOAT",
    armPayload: 3,
    armReach: 855,
    armDof: 7,
    remarks: "Research-grade collaborative robot with integrated torque sensors in all joints",
  },
  {
    name: "Clearpath Ridgeback",
    manufacturer: "Clearpath Robotics",
    type: "mobile_base",
    length: 960,
    width: 823,
    height: 410,
    weight: 145,
    usablePayload: 100,
    functions: "Heavy payload transport, research platform",
    reach: null,
    driveSystem: "Omnidirectional (Mecanum wheels)",
    certifications: "CE, FCC",
    rosCompatible: 1,
    rosDistros: "Noetic, Humble",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 480,
    batteryLife: 480,
    maxSpeed: 1100,
    forceSensor: 0,
    eoatCompatibility: null,
    armPayload: null,
    armReach: null,
    armDof: null,
    remarks: "Heavy-duty omnidirectional mobile base for research and industrial applications",
  },
];

async function seedDatabase() {
  console.log("Starting database seeding...");
  
  try {
    for (const robot of sampleRobots) {
      await db.insert(robots).values(robot);
      console.log(`✓ Added: ${robot.name}`);
    }
    
    console.log("\n✅ Database seeded successfully!");
    console.log(`Total robots added: ${sampleRobots.length}`);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
  
  process.exit(0);
}

seedDatabase();
