CREATE TABLE `robots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`manufacturer` varchar(255),
	`robot_type` enum('mobile_manipulator','mobile_base','manipulator_arm') NOT NULL,
	`length` int,
	`width` int,
	`height` int,
	`weight` int,
	`usable_payload` int,
	`functions` text,
	`reach` int,
	`drive_system` varchar(255),
	`certifications` text,
	`ros_compatible` int DEFAULT 0,
	`ros_distros` text,
	`sdk_available` int DEFAULT 0,
	`api_available` int DEFAULT 0,
	`operation_time` int,
	`battery_life` int,
	`max_speed` int,
	`force_sensor` int DEFAULT 0,
	`eoat_compatibility` text,
	`arm_payload` int,
	`arm_reach` int,
	`arm_dof` int,
	`remarks` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_by` int,
	CONSTRAINT `robots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `robots` ADD CONSTRAINT `robots_created_by_users_id_fk` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;